# eslint-disable no-irregular-whitespace, yaml/no-irregular-whitespace
# prettier-ignore
name: â€ƒ

on:
  workflow_call:
    inputs:
      ref:
        description: "Force checkout a specific git ref (branch, tag, commit)"
        type: string

concurrency:
  group: deploy
  cancel-in-progress: false # canceling could break state

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: Publish
        run: pnpm publish --no-git-checks --tag $(npx simple-dist-tag)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
