# eslint-disable no-irregular-whitespace, yaml/no-irregular-whitespace
# prettier-ignore
name: â€ƒ

on:
  workflow_call:
    inputs:
      ref:
        description: "Force checkout a specific git ref (branch, tag, commit)"
        type: string

concurrency:
  group: deploy
  cancel-in-progress: false # canceling could break state

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      # - name: Extract version (short hash of latest commit)
      #   id: version
      #   if: inputs.env == 'staging'
      #   run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Publish
        run: pnpm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
